import SwiftUI
import WebKit

struct ProjectToolbarView: View {
    let project: ShaderProject
    @EnvironmentObject var projectsViewModel: ProjectsViewModel
    
    @State private var showingExportSheet = false
    @State private var showingRenameAlert = false
    @State private var newProjectName = ""
    @State private var showingFullScreenPreview = false
    
    var body: some View {
        HStack(spacing: 8) {
            
            
            Button(action: {
                projectsViewModel.saveProject(project)
            }) {
                Text("Save")
                    .bold()
                    .foregroundStyle(.primary)
            }


            Button(action: {
                showingFullScreenPreview = true
            }) {
                Image(systemName: "arrow.up.left.and.arrow.down.right")
                    .foregroundColor(.primary)
            }
            
            Menu {
                Button(action: { showingRenameAlert = true }) {
                    Label("Rename", systemImage: "pencil")
                }
                
                Button(action: {
                    _ = projectsViewModel.duplicateProject(project)
                }) {
                    Label("Duplicate", systemImage: "doc.on.doc")
                }
                
                Divider()
                
                Button(action: { showingExportSheet = true }) {
                    Label("Export", systemImage: "square.and.arrow.up")
                }
            } label: {
                Image(systemName: "ellipsis.circle")
                    .foregroundColor(.primary)
            }
            
            
        }
        .alert("Rename Project", isPresented: $showingRenameAlert) {
            TextField("Project Name", text: $newProjectName)
            Button("Cancel", role: .cancel) {}
            Button("Rename") {
                if !newProjectName.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                    project.name = newProjectName.trimmingCharacters(in: .whitespacesAndNewlines)
                    projectsViewModel.saveProject(project)
                }
            }
        } message: {
            Text("Enter a new name for this project")
        }
        .sheet(isPresented: $showingExportSheet) {
            EnhancedExportSheet(project: project)
        }
        .fullScreenCover(isPresented: $showingFullScreenPreview) {
            FullScreenPreviewView(project: project)
        }
        .onAppear {
            newProjectName = project.name
        }
    }
}

struct ExportSheet: View {
    let project: ShaderProject
    @Environment(\.dismiss) private var dismiss
    
    var body: some View {
        NavigationView {
            VStack(spacing: 24) {
                Text("Export Project")
                    .font(.largeTitle)
                    .fontWeight(.bold)
                
                VStack(spacing: 16) {
                    ExportOption(
                        title: "Export as Image",
                        description: "Save current frame as PNG",
                        icon: "photo"
                    ) {
                        // TODO: Implement image export
                        dismiss()
                    }
                    
                    ExportOption(
                        title: "Export Shader Code",
                        description: "Share vertex and fragment shaders",
                        icon: "doc.text"
                    ) {
                        exportShaderCode()
                        dismiss()
                    }
                    
                    ExportOption(
                        title: "Export Project",
                        description: "Save complete project file",
                        icon: "folder"
                    ) {
                        // TODO: Implement project export
                        dismiss()
                    }
                }
                
                Spacer()
            }
            .padding()
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Done") {
                        dismiss()
                    }
                }
            }
        }
    }
    
    private func exportShaderCode() {
        guard let vertexShader = project.vertexShader,
              let fragmentShader = project.fragmentShader else { return }
        
        let exportText = """
// \(project.name)
// Generated by GLSL Studio

// Vertex Shader
\(vertexShader.content)

// Fragment Shader
\(fragmentShader.content)
"""
        
        let activityController = UIActivityViewController(
            activityItems: [exportText],
            applicationActivities: nil
        )
        
        if let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
           let window = windowScene.windows.first {
            window.rootViewController?.present(activityController, animated: true)
        }
    }
}

struct ExportOption: View {
    let title: String
    let description: String
    let icon: String
    let action: () -> Void
    
    var body: some View {
        Button(action: action) {
            HStack(spacing: 16) {
                Image(systemName: icon)
                    .font(.title2)
                    .foregroundColor(.accentColor)
                    .frame(width: 32, height: 32)
                
                VStack(alignment: .leading, spacing: 4) {
                    Text(title)
                        .font(.headline)
                        .foregroundColor(.primary)
                    
                    Text(description)
                        .font(.body)
                        .foregroundColor(.secondary)
                }
                
                Spacer()
                
                Image(systemName: "chevron.right")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            .padding()
            .background(Color(.systemGray6))
            .cornerRadius(12)
        }
        .buttonStyle(PlainButtonStyle())
    }
}

struct FullScreenPreviewView: View {
    let project: ShaderProject
    @Environment(\.dismiss) private var dismiss
    @StateObject private var webGLService = WebGLService()
    @State private var showFPS = true
    
    var body: some View {
        ZStack {
            Color.black.ignoresSafeArea()
            
            FullScreenWebGLPreviewView(
                project: project,
                webGLService: webGLService,
                showFPS: $showFPS
            )
            .ignoresSafeArea()
            .onChange(of: project.vertexShader?.content) { oldValue, newValue in
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                    webGLService.updateShaders(
                        vertexShader: project.vertexShader?.content ?? "",
                        fragmentShader: project.fragmentShader?.content ?? ""
                    )
                }
            }
            .onChange(of: project.fragmentShader?.content) { oldValue, newValue in
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                    webGLService.updateShaders(
                        vertexShader: project.vertexShader?.content ?? "",
                        fragmentShader: project.fragmentShader?.content ?? ""
                    )
                }
            }
            
            if let error = webGLService.compileError {
                VStack {
                    HStack {
                        VStack(alignment: .leading, spacing: 8) {
                            HStack {
                                Image(systemName: "exclamationmark.triangle.fill")
                                    .foregroundColor(.red)
                                Text("Shader Error")
                                    .font(.headline)
                                    .foregroundColor(.red)
                            }
                            
                            ScrollView {
                                Text(error)
                                    .font(.system(.caption, design: .monospaced))
                                    .foregroundColor(.primary)
                                    .frame(maxWidth: .infinity, alignment: .leading)
                            }
                            .frame(maxHeight: 200)
                        }
                        
                        Spacer()
                    }
                    .padding()
                    .background(Color(.systemBackground).opacity(0.95))
                    .cornerRadius(12)
                    .shadow(radius: 8)
                    
                    Spacer()
                }
                .padding()
            }
            
            VStack {
                HStack {
                    Button(action: {
                        dismiss()
                    }) {
                        Image(systemName: "xmark")
                            .foregroundColor(.white)
                            .frame(width: 32, height: 32)
                            .padding(4)
                            .background(Color.black.opacity(0.6))
                            .clipShape(Circle())
                    }
                    

                    Spacer()
                    
                    if showFPS {
                        VStack(alignment: .trailing, spacing: 4) {
                            Text("FPS: \(Int(webGLService.fps))")
                                .font(.system(.caption, design: .monospaced))
                                .foregroundColor(.white)
                            Text("Render: \(String(format: "%.1f", webGLService.renderTime))ms")
                                .font(.system(.caption, design: .monospaced))
                                .foregroundColor(.white)
                        }
                        .padding(12)
                        .background(Color.black.opacity(0.7))
                        .cornerRadius(12)
                        .onTapGesture {
                            showFPS = false
                        }
                    }
                }
                .padding()
                
                Spacer()
            }
        }
        .onTapGesture(count: 2) {
            if !showFPS {
                showFPS = true
            }
        }
        .gesture(
            TapGesture(count: 2)
                .onEnded {
                    if !showFPS {
                        showFPS = true
                    }
                }
        )
    }
}

struct FullScreenWebGLPreviewView: UIViewRepresentable {
    let project: ShaderProject
    let webGLService: WebGLService
    @Binding var showFPS: Bool
    
    func makeUIView(context: Context) -> WKWebView {
        let webView = webGLService.setupWebView()
        
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
            updateShaders()
        }
        
        return webView
    }
    
    func updateUIView(_ webView: WKWebView, context: Context) {
        webGLService.setGeometry(.quad)
    }
    
    private func updateShaders() {
        guard let vertexShader = project.vertexShader,
              let fragmentShader = project.fragmentShader else { 
            return 
        }
        
        webGLService.updateShaders(
            vertexShader: vertexShader.content,
            fragmentShader: fragmentShader.content
        )
    }
}
